### ISSUE TITLE
Create resources dir and move less/locale

### ISSUE THREAD

**Issue by Ralkage** [FriendsOfFlarum/extension-generator#1]
As the title suggests, we should move the less/locale folders into a resources folder to reduce chaos.

**Comment by dsevillamartin** [comment]
I’ll make it an option enabled by default.

**Comment by dsevillamartin** [comment]
Closed with https://github.com/ReFlar/extension-generator/commit/84115bf0473fa97bafc00db5b510ef5c046257aa
