### ISSUE TITLE
Invalid package name format

### ISSUE THREAD

**Issue by Justman10000** [FriendsOfFlarum/extension-generator#15]
Hi, I entered the title of the package for the first question, but then this came up:

> Invalid package name format

**Comment by datitisev** [comment]
The package name is `<vendor>/<name>`, as the prompt indicates. E.g. `flarum/core` would be a package name.

**Comment by Ralkage** [comment]
Greetings @Justman10000,

This package is no longer supported. Please use https://github.com/flarum/cli instead.
