### ISSUE TITLE
Feature Request: Add Examples Next To Prompted Questions (In Parenthesis)

### ISSUE THREAD

**Issue by Ralkage** [FriendsOfFlarum/extension-generator#5]
**Is your feature request related to a problem? Please describe.**
For new users or for those who are not used to memorizing the generator prompts, it can be time consuming and slightly annoying to remember what to put for each of the prompts as answers.

**Describe the solution you'd like**
What I would like to have happen is that for each prompt, add a parenthesis with an example such as the following:

* Package (Vendor/Name): 

or 

* Package (e.g. ReFlar/Sample-Extension):

**Describe alternatives you've considered**
None.

**Additional context**
Only add to those that it should obviously apply to.

**Comment by dsevillamartin** [comment]
Does the following look good?
The only way to implement this and still look good was to make it a default value, and then not allow it during validation.
Note: `Author` in package & namespace have been replaced with `Vendor` (no longer mismatched like in recording).

[![asciicast](https://asciinema.org/a/usmk9ofSytcG6SXDdpPtqBUsB.png)](https://asciinema.org/a/usmk9ofSytcG6SXDdpPtqBUsB)

Also, the color is closer to the following (at least on my terminal). By default there's more difference:
![image](https://user-images.githubusercontent.com/6401250/42653686-26e9e3a8-85e4-11e8-8200-bd92608f7e86.png)

**Comment by dsevillamartin** [comment]
Modified to have the value at the left and removed `default` implementation (only UI change).

**Comment by dsevillamartin** [comment]
![image](https://user-images.githubusercontent.com/6401250/42655187-4313605e-85e9-11e8-943d-877a14833fd2.png)
