### ISSUE TITLE
Feature Request: Add Shortcut Command to Call Extension Generator

### ISSUE THREAD

**Issue by Ralkage** [FriendsOfFlarum/extension-generator#6]
**Is your feature request related to a problem? Please describe.**
It can be time consuming and slightly annoying to call the full package by it's long command name `create-flarum-extension`.

**Describe the solution you'd like**
What I would like to have happen is that there should be a shorter/abbreviated command to call the `create-flarum-extension` package such as `cfe my-extension`

**Describe alternatives you've considered**
None.

**Additional context**
Allow both options.

**Comment by dsevillamartin** [comment]
Done!

![image](https://user-images.githubusercontent.com/6401250/42653923-e1d5dfc8-85e4-11e8-8aaa-77bcb4491ab9.png)
![image](https://user-images.githubusercontent.com/6401250/42653930-e9b1c68a-85e4-11e8-890d-633e446164d1.png)
